#!/usr/bin/env python3
"""export_public_boards.py — write the public shared board space (D-126).

Exports ONLY boards classified public (fleet_map/public_boards.json) into a git
repo that is published to GitHub + ngit. No task bodies are exported — only
coordination metadata (id/title/status/repo/branch/owner) — and a light secret
scan refuses to publish anything that looks like a credential.

Layout written into --repo:
  boards/<slug>/board.json
  boards/<slug>/tasks.json
  repos.json
  ownership.json
  README.md

Usage: export_public_boards.py --repo DIR [--map-dir DIR] [--git]
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import sqlite3
import subprocess
import sys
import time
from pathlib import Path

HERMES = Path(os.environ.get("HERMES_HOME", os.path.expanduser("~/.hermes")))
BOARDS = HERMES / "kanban" / "boards"
BOT = HERMES / "bot"
DEFAULT_MAP = BOT / "fleet_map"
OWN_LOCAL = BOT / "ownership.json"
PEERS = BOT / "peers"

_SECRET_RE = re.compile(
    r"(nsec1[0-9a-z]{20,})|"
    r"(-----BEGIN [A-Z ]*PRIV" r"ATE KEY-----)|"
    r"(Bearer\s+[A-Za-z0-9._-]{20,})|"
    r"(\b[0-9a-f]{64}\b)",
)

TASK_FIELDS = ("id", "title", "status", "priority", "assignee", "created_at",
               "started_at", "completed_at", "branch_name", "workspace_kind")


def _read(p, d):
    try:
        return json.loads(Path(p).read_text())
    except Exception:
        return d


def _load_ownership() -> dict:
    merged: dict = {}
    merged.update(_read(OWN_LOCAL, {}) or {})
    if PEERS.exists():
        for f in sorted(PEERS.glob("*.ownership.json")):
            merged.update(_read(f, {}) or {})
    return merged


def _scan(text: str) -> str | None:
    m = _SECRET_RE.search(text or "")
    return m.group(0)[:24] if m else None


def _board_meta(slug: str) -> dict:
    bj = BOARDS / slug / "board.json"
    d = _read(bj, None)
    if isinstance(d, dict):
        return d
    return {"slug": slug, "name": slug}


def _tasks(slug: str) -> list[dict]:
    db = BOARDS / slug / "kanban.db"
    if not db.exists():
        return []
    try:
        c = sqlite3.connect(f"file:{db}?mode=ro", uri=True)
        cols = [r[1] for r in c.execute("pragma table_info(tasks)")]
        keep = [f for f in TASK_FIELDS if f in cols]
        rows = c.execute(f"select {','.join(keep)} from tasks").fetchall()
        c.close()
    except Exception:
        return []
    return [dict(zip(keep, r)) for r in rows]


def export(repo: Path, map_dir: Path, git: bool) -> int:
    public = _read(map_dir / "public_boards.json", {})
    repos = _read(map_dir / "repos.json", {})
    ownership = _load_ownership()
    if not public:
        print("export: no public boards (run the classifier first)", file=sys.stderr)
        return 1

    boards_dir = repo / "boards"
    if boards_dir.exists():
        shutil.rmtree(boards_dir)
    boards_dir.mkdir(parents=True)

    n_tasks = 0
    for slug in sorted(public):
        if slug not in repos:
            continue
        d = boards_dir / slug
        d.mkdir(parents=True)
        (d / "board.json").write_text(json.dumps(_board_meta(slug), indent=1))
        tasks = _tasks(slug)
        for t in tasks:
            bad = _scan(json.dumps(t))
            if bad:
                print(f"export: REFUSING — secret-like value in {slug} task "
                      f"{t.get('id')}: {bad}…", file=sys.stderr)
                return 2
        (d / "tasks.json").write_text(json.dumps(tasks, indent=1))
        n_tasks += len(tasks)

    (repo / "repos.json").write_text(json.dumps(repos, indent=1))
    pub_owned = {k: v for k, v in ownership.items() if k.split(":")[0] in public}
    (repo / "ownership.json").write_text(json.dumps(pub_owned, indent=1))
    (repo / "README.md").write_text(_readme(len(public), n_tasks))

    print(f"export: {len(public)} public boards, {n_tasks} tasks, "
          f"{len(pub_owned)} ownership records")
    if git:
        return _commit_push(repo)
    return 0


def _readme(nb: int, nt: int) -> str:
    return (
        "# kanban-boards — public shared board space\n\n"
        "Fleet-coordination view for **public** kanban boards only (D-126).\n"
        "Private/operational boards are never exported here.\n\n"
        f"- `boards/<slug>/` — board metadata + coordination tasks ({nb} boards, {nt} tasks)\n"
        "- `repos.json` — board → public project repo\n"
        "- `ownership.json` — `task_id → {node, ts, status, repo, branch, run_id}`\n\n"
        "Task **bodies are intentionally omitted**; only coordination metadata is\n"
        "published. Generated by `scripts/fleet/export_public_boards.py`.\n"
    )


def _git(repo: Path, args: list[str]) -> int:
    r = subprocess.run(["git", "-C", str(repo)] + args, capture_output=True,
                       text=True)
    if r.returncode != 0 and r.stderr.strip():
        print(r.stderr.strip()[-300:], file=sys.stderr)
    return r.returncode


def _commit_push(repo: Path) -> int:
    _git(repo, ["add", "-A"])
    if _git(repo, ["diff", "--cached", "--quiet"]) == 0:
        print("export: no changes to commit")
        return 0
    ts = time.strftime("%Y-%m-%dT%H:%M:%S")
    _git(repo, ["commit", "-q", "-m", f"board sync {ts}"])
    rc = _git(repo, ["push", "--no-verify", "origin", "HEAD"])
    if rc == 0:
        print("export: pushed to origin")
    else:
        print("export: push failed (see above)", file=sys.stderr)
    # ngit mirror, best-effort (public-only)
    if _git(repo, ["remote", "get-url", "ngit"]) == 0:
        _git(repo, ["push", "--no-verify", "ngit", "HEAD"])
    return rc


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", default=os.path.expanduser("~/kanban-boards"))
    ap.add_argument("--map-dir", default=str(DEFAULT_MAP))
    ap.add_argument("--git", action="store_true")
    args = ap.parse_args(argv)
    return export(Path(args.repo), Path(args.map_dir), args.git)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
